Gcloud functions gen2 tests
eastlondoner/remix pull request #1
Opened 2022-06-06 16:54 UTC by penx

Add unit tests to [gcloud-functions-gen2](https://github.com/eastlondoner/remix/tree/gcloud-functions-gen2) branch.

These are the Express unit tests, updated to use `getTestServer` and `http` from `@google-cloud/functions-framework` so that they behave as per google cloud functions (e.g. rawBody is present on request).

These require Jest@28 which is in PR at https://github.com/remix-run/remix/pull/3400, and can be manually updated to see the tests pass.

2022-06-06 16:58 UTC, MichaelDeBoey requested changes

2022-06-06 16:58 UTC, MichaelDeBoey commented on packages/remix-gcloud-functions-gen2/__tests__/server-test.ts
> +describe("express createRequestHandler", () => {
```suggestion
describe("google-cloud-functions createRequestHandler", () => {
```

2022-06-06 16:58 UTC, MichaelDeBoey commented on packages/remix-gcloud-functions-gen2/__tests__/server-test.ts
> +describe("express createRemixHeaders", () => {
```suggestion
describe("google-cloud-functions createRemixHeaders", () => {
```

2022-06-06 16:58 UTC, MichaelDeBoey commented on packages/remix-gcloud-functions-gen2/__tests__/server-test.ts
> +describe("express createRemixRequest", () => {
```suggestion
describe("google-cloud-functions createRemixRequest", () => {
```

2022-06-06 16:58 UTC, MichaelDeBoey commented on packages/remix-gcloud-functions-gen2/jest.config.js
> +  displayName: "gcloud-functions-gen2",
```suggestion
  displayName: "google-cloud-functions",
```

2022-06-06 20:46 UTC, eastlondoner commented
@penx I think we need to add a devDependency on `@google-cloud/functions-framework` so the tests can run - CI fails with 

Is there anything these tests are doing that specifically requires `Jest@28` ?

2022-06-06 20:55 UTC, penx commented
```ts
import { getTestServer } from "@google-cloud/functions-framework/testing";
```

This import makes use of [package exports](https://nodejs.org/api/packages.html#exports):

https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/759aac18ad297363c4651efcf19ab2bf8fa9625a/package.json#L13

Full support for this [was added in Jest 28](https://jestjs.io/blog/2022/04/25/jest-28#packagejson-exports).

In Jest 27,  server-test.ts will fail saying it cannot find `@google-cloud/functions-framework/testing`.

2022-06-06 21:00 UTC, penx commented
> I think we need to add a devDependency on @google-cloud/functions-framework so the tests can run - CI fails with

It's in the devDependencies for the package already

https://github.com/penx/remix/blob/689da9c07f674be05d3b802b83afaa8aa3bd34bb/packages/remix-gcloud-functions-gen2/package.json#L20-L22

And as per the comment at https://github.com/remix-run/remix/pull/2266#discussion_r889528068, this should be moved to dependencies.

This should be sufficient - the two remaining issues are that I didn't update the lock file in this PR and that Jest 27 will complain about a missing export as per my other comment.

2022-06-06 21:09 UTC, MichaelDeBoey commented
@penx Now that https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/461 is merged, do we still need `jest` v28?

2022-06-06 21:19 UTC, penx commented
@MichaelDeBoey as discussed on discord, yes, so that the `/testing` import is supported

2022-06-06 21:34 UTC, eastlondoner commented
> > I think we need to add a devDependency on @google-cloud/functions-framework so the tests can run - CI fails with
> 
> It's in the devDependencies for the package already
> 
> https://github.com/penx/remix/blob/689da9c07f674be05d3b802b83afaa8aa3bd34bb/packages/remix-gcloud-functions-gen2/package.json#L20-L22
> 
> And as per the comment at [remix-run#2266 (comment)](https://github.com/remix-run/remix/pull/2266#discussion_r889528068), this should be moved to dependencies.
> 
> This should be sufficient - the two remaining issues are that I didn't update the lock file in this PR and that Jest 27 will complain about a missing export as per my other comment.

OK, currently this is failing with being unable to import though...
```
Summary of all failing tests
[83](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:84)
FAIL packages/remix-gcloud-functions-gen2/__tests__/server-test.ts
[84](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:85)
  ● Test suite failed to run
[85](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:86)
[86](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:87)
    Cannot find module '@google-cloud/functions-framework/testing' from '__tests__/server-test.ts'
[87](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:88)
[88](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:89)
       8 | import { http } from "@google-cloud/functions-framework";
[89](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:90)
       9 | // @ts-ignore
[90](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:91)
    > 10 | import { getTestServer } from "@google-cloud/functions-framework/testing";
[91](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:92)
         | ^
[92](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:93)
      11 |
[93](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:94)
      12 | import {
[94](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:95)
      13 |   createRemixHeaders,
[95](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:96)
[96](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:97)
      at Resolver.resolveModule (../../node_modules/jest-resolve/build/resolver.js:324:11)
[97](https://github.com/eastlondoner/remix/runs/6762836078?check_suite_focus=true#step:6:98)
      at Object.<anonymous> (__tests__/server-test.ts:10:1)
```

2022-06-06 21:37 UTC, penx commented
Yes that is the jest issue that requires updating to v28 to support package.json exports

2022-06-08 06:09 UTC, eastlondoner commented
Thanks @penx ! I cherry-picked the relevant commits from this PR into https://github.com/eastlondoner/remix/tree/gcloud-functions-gen2 after I rebased on the `dev` branch (to save you needing to rebase this).

Closing this PR because it's no longer needed after that cherry-pick.

2022-06-08 06:09 UTC, closed without merging